import React, { useState } from "react";
import {
  FaFacebook,
  FaInstagram,
  FaTwitter,
  FaPinterest,
} from "react-icons/fa";
import { RiMagicLine } from "react-icons/ri";
import sideimg from "../../assets/marketing assets/aa.png";
import { Alert, Snackbar } from "@mui/material";
import { useNavigate } from "react-router-dom";
function MarketingHome() {
  const navigate = useNavigate();
  const [click, setClick] = useState(false);
  const handleClick = () => {
    setClick(false);
  };

  const handleNavigate = () => {
    navigate(`/marketing/${click}`);
  };
  return (
    <div className=" w-full h-screen px-5 py-5">
      <div className=" h-screen w-full flex justify-evenly items-center ">
        <div className="flex flex-col gap-6">
          <div className="flex flex-col">
            <h1 className=" text-3xl">Social Media Management</h1>
            <h1 className=" text-sm">
              Attach a profile to see how cashery can help your business
            </h1>
          </div>
          <div className=" flex flex-col gap-6">
            <h1 className=" text-xl">Connect your profile</h1>
            <div className=" flex flex-col gap-5">
              <div className=" flex gap-5">
                <div
                  onClick={() => setClick(true)}
                  className=" shadow-lg flex justify-center items-center px-3 py-2 gap-3 cursor-pointer bg-[#0066ff] rounded text-white hover:scale-110 duration-700"
                >
                  <FaFacebook className=" text-2xl" /> Facebook page
                </div>
                <div
                  onClick={() => setClick(true)}
                  className=" shadow-lg flex justify-center items-center px-3 py-1 gap-3 cursor-pointer bg-[#FF006B] rounded text-white hover:scale-110 duration-700"
                >
                  <FaInstagram className=" text-2xl" /> Instagram profile
                </div>
              </div>
              <div className=" flex gap-5">
                <div
                  onClick={() => setClick(true)}
                  className=" shadow-lg flex justify-center items-center px-3 py-2 gap-3 cursor-pointer bg-[#0066ff] rounded text-white hover:scale-110 duration-700"
                >
                  <FaTwitter className=" text-2xl" /> Twitter
                </div>
                <div
                  onClick={() => setClick(true)}
                  className=" shadow-lg flex justify-center items-center px-3 py-1 cursor-pointer gap-3 bg-red-500 rounded text-white hover:scale-110 duration-700"
                >
                  <FaPinterest /> Pintrest profile
                </div>
              </div>
            </div>
            <h1 className="px-3 py-2 bg-gray-200 rounded shadow-sm">
              Poster,content,hastags will be generated by AI
            </h1>
            <div className=" w-44 h-12 flex items-center cursor-pointer text-white justify-center bg-blue-500 rounded-xl hover:scale-110 duration-500 mb-20">
              <h1 className=" flex gap-2 items-center" onClick={handleNavigate}>
                Generate Posts <RiMagicLine className=" text-xl" />
              </h1>
            </div>
            <Snackbar
              open={click}
              autoHideDuration={6000}
              onClose={handleClick}
            >
              <Alert onClose={handleClick} severity="success">
                connected to the profile
              </Alert>
            </Snackbar>
          </div>
        </div>
        <div>
          <div className=" flex flex-col gap-10">
            <img src={sideimg} alt="" width={500} />
          </div>
        </div>
      </div>
    </div>
  );
}

export default MarketingHome;
